### ISSUE TITLE
Plugin sets laststatus=2

### ISSUE THREAD

**Issue by igorlfs** [cameron-wags/rainbow_csv.nvim#17]
Hello,

for some reason, the plugin sets laststatus to 2 every time a csv buffer is focused. Why is it like that? Could we have an option to disable that?

**Comment by cameron-wags** [comment]
It's the behavior of the original rainbow_csv plugin. The statusline becomes a reference for shorthand column names when writing RBQL queries using `:Select`, `:Update`, or `:RbSelect`. 

It looks like this when active:
![statusline](https://github.com/cameron-wags/rainbow_csv.nvim/assets/38019188/f8760c5f-08c8-457b-a38e-77fefbd77988)

I understand that setting `statusline=2` might be disruptive. If you don't mind losing the feature above, I just added `g:disable_rainbow_statusline` in a520dab to disable it.

**Comment by igorlfs** [comment]
Thanks!
