### ISSUE TITLE
disable_rainbow_hover in lazyvim

### ISSUE THREAD

**Issue by GladioFeng** [cameron-wags/rainbow_csv.nvim#18]
# lazyvim config for disable ranibow hover
in vimrc with let g:disable_rainbow_hover = 1 to disable hover, how can i config this setting with lazyvim? sorry, I am a lua rookie.🥹🥹🥹
<img width="1169" alt="image" src="https://github.com/cameron-wags/rainbow_csv.nvim/assets/100987925/6486e36b-8d82-4fbc-91e3-478c95fbb0b8">

**Comment by cameron-wags** [comment]
You can call `vim.g.disable_rainbow_hover = 1` in lua anytime before the plugin loads.

In the lazy spec that's done like this:

```lua
{
	'cameron-wags/rainbow_csv.nvim',
	config = function ()
		vim.g.disable_rainbow_hover = 1
		require 'rainbow_csv'.setup()
	end,
	-- ...
},
```

**Comment by GladioFeng** [comment]
thanks. it works. 😁
