### ISSUE TITLE
Set number should be setlocal

### ISSUE THREAD

**Issue by bluss** [cameron-wags/rainbow_csv.nvim#20]
Hi, thanks for the nice plugin.

You have a 'set number' or similar in the plugin, but it would be great if this was setlocal or similar, so it doesn't change settings for non-csv buffers (and buffers opened after the csv buffer)

**Comment by cameron-wags** [comment]
Thanks for letting me know!

Should be resolved by 5033e3abd4fb0a0ee07232530a032296535704b4

**Comment by bluss** [comment]
thanks!
