### ISSUE TITLE
script_folder_path resolution error in Windows.

### ISSUE THREAD

**Issue by aloknigam247** [cameron-wags/rainbow_csv.nvim#22]
Hi,

I get `Unable to find plugin install folder in runtimepath.` everytime I try to open csv files using this plugin.
I could find that lines mentioned in the code reference below is using unix path, and if fails to resolve for windows.

```lua
local script_folder_path = (function()
	for _, path in ipairs(vim.fn.globpath(vim.o.rtp, 'rbql_core/', 0, 1)) do
		if string.find(path, '/rainbow_csv.nvim/rbql_core/') ~= nil then
			return path:gsub('/rbql_core/', '')
		end
	end
	notify_warn 'Unable to find plugin install folder in runtimepath.'
	return nil
end)()
```
[reference](https://github.com/cameron-wags/rainbow_csv.nvim/blob/5033e3abd4fb0a0ee07232530a032296535704b4/lua/rainbow_csv/fns.lua#L40C1-L44C5)

**Comment by zhyzky** [comment]
Maybe change to
···
local script_folder_path = (function()
	for _, path in ipairs(vim.fn.globpath(vim.o.rtp, 'rbql_core/', 0, 1)) do
		if string.find(path, 'rainbow_csv.nvim') ~= nil then
			return string.sub(path, 1, -12)
		end
	end
	notify_warn 'Unable to find plugin install folder in runtimepath.'
	return nil
end)()
···

**Comment by eduardomezencio** [comment]
I opened a PR to try to fix this, could you test it?

**Comment by aloknigam247** [comment]
@eduardomezencio . I tested it in windows. It worked without error and in my case value of `script_folder_path` is `D:/apps/nvim-data/lazy/rainbow_csv.nvim` which is root of rainbow_csv installation.
